name: Package Pre-Compiled KernelSU (Jasmine Sprout)

# This allows you to trigger the packaging manually
on:
  workflow_dispatch:

jobs:
  build:
    name: Zip Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v4

      - name: Package the Kernel Zip
        run: |
          # This command zips all files in the repository.
          # The '-x' flags tell it to ignore hidden GitHub folders so your zip stays clean.
          zip -r9 Scarlet-KernelSU-Jasmine-ArrowOS.zip * -x ".git*" -x ".github*"

      - name: Upload Kernel as Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scarlet-KernelSU-Jasmine
          path: Scarlet-KernelSU-Jasmine-ArrowOS.zip
